/**
 * Patches blakejs and @zk-kit/eddsa-poseidon for ESM/CJS compatibility.
 *
 * Problem 1: @zk-kit/eddsa-poseidon is pure ESM and does named imports from blakejs,
 * which is CJS-only. Node.js 22 can't statically resolve named exports from CJS
 * modules whose exports depend on runtime require() calls.
 * Fix: Add an `exports` field to blakejs/package.json pointing `import` at a
 * thin ESM wrapper that loads the CJS module via createRequire and re-exports.
 *
 * Problem 2: @zk-kit/eddsa-poseidon@1.1.0 declares a `"./blake-2b"` subpath export
 * with a CJS condition pointing to dist/lib.commonjs/eddsa-poseidon-blake-2b.cjs,
 * but that file is missing from the published package. Vercel's bundler uses require()
 * which hits this broken CJS condition and crashes.
 * Fix: Create the missing directory and a CJS stub that re-exports from the main index.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";

// ── Patch 1: blakejs ESM shim ──────────────────────────────────────────────

const blakePkgPath = "./node_modules/blakejs/package.json";
const blakeShimPath = "./node_modules/blakejs/esm.mjs";

if (!existsSync(blakePkgPath)) {
  console.log("blakejs not found — skipping blakejs patch");
} else {
  const pkg = JSON.parse(readFileSync(blakePkgPath, "utf8"));

  if (pkg.exports) {
    console.log("blakejs already has exports — skipping blakejs patch");
  } else {
    pkg.exports = {
      ".": {
        import: "./esm.mjs",
        require: "./index.js",
        default: "./index.js",
      },
    };

    const shim = `// ESM re-export shim — auto-generated by patch-blakejs.mjs
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const pkg = require("./index.js");
export const {
  blake2b, blake2bHex, blake2bInit, blake2bUpdate, blake2bFinal,
  blake2s, blake2sHex, blake2sInit, blake2sUpdate, blake2sFinal,
} = pkg;
export default pkg;
`;

    writeFileSync(blakePkgPath, JSON.stringify(pkg, null, 2) + "\n");
    writeFileSync(blakeShimPath, shim);
    console.log("Patched blakejs: added ESM named-export shim");
  }
}

// ── Patch 2: @zk-kit/eddsa-poseidon missing CJS file ──────────────────────
//
// @zk-kit/eddsa-poseidon@1.1.0 declares:
//   "./blake-2b": { "require": "./dist/lib.commonjs/eddsa-poseidon-blake-2b.cjs" }
// but that file was never published. Vercel's nft bundler and Node's require()
// both hit this broken condition.
//
// Two-part fix:
//   (a) Patch package.json to redirect "require" to the existing ./dist/index.cjs
//       so Vercel's nft tracer includes the right file in the function bundle.
//   (b) Also create the stub file so any code that resolves the literal path works.

const eddsaPkgPath = "./node_modules/@zk-kit/eddsa-poseidon/package.json";
const eddsaCjsDir = "./node_modules/@zk-kit/eddsa-poseidon/dist/lib.commonjs";
const eddsaCjsStub = `${eddsaCjsDir}/eddsa-poseidon-blake-2b.cjs`;
const eddsaMainCjs = "./node_modules/@zk-kit/eddsa-poseidon/dist/index.cjs";

if (!existsSync(eddsaPkgPath)) {
  console.log("@zk-kit/eddsa-poseidon not found — skipping eddsa-poseidon patch");
} else {
  const eddsaPkg = JSON.parse(readFileSync(eddsaPkgPath, "utf8"));

  // (a) Redirect the broken "require" export to the existing CJS index
  const blake2bExport = eddsaPkg.exports?.["./blake-2b"];
  if (blake2bExport && blake2bExport.require !== "./dist/index.cjs") {
    blake2bExport.require = "./dist/index.cjs";
    writeFileSync(eddsaPkgPath, JSON.stringify(eddsaPkg, null, 2) + "\n");
    console.log("Patched @zk-kit/eddsa-poseidon: redirected ./blake-2b require → ./dist/index.cjs");
  } else {
    console.log("@zk-kit/eddsa-poseidon package.json already patched — skipping");
  }

  // (b) Also create the stub at the original path (belt-and-suspenders)
  if (!existsSync(eddsaCjsStub) && existsSync(eddsaMainCjs)) {
    mkdirSync(eddsaCjsDir, { recursive: true });
    const stub = `// CJS stub — auto-generated by patch-blakejs.mjs
// @zk-kit/eddsa-poseidon@1.1.0 references this file in its exports but never published it.
"use strict";
module.exports = require("../index.cjs");
`;
    writeFileSync(eddsaCjsStub, stub);
    console.log("Patched @zk-kit/eddsa-poseidon: created missing CJS stub file");
  }
}
