/**
 * Patches blakejs and @zk-kit/eddsa-poseidon for ESM/CJS compatibility.
 *
 * Problem 1: @zk-kit/eddsa-poseidon is pure ESM and does named imports from blakejs,
 * which is CJS-only. Node.js 22 can't statically resolve named exports from CJS
 * modules whose exports depend on runtime require() calls.
 * Fix: Add an `exports` field to blakejs/package.json pointing `import` at a
 * thin ESM wrapper that loads the CJS module via createRequire and re-exports.
 *
 * Problem 2: @zk-kit/eddsa-poseidon@1.1.0 declares a `"./blake-2b"` subpath export
 * with a CJS condition pointing to dist/lib.commonjs/eddsa-poseidon-blake-2b.cjs,
 * but that file is missing from the published package. Vercel's bundler uses require()
 * which hits this broken CJS condition and crashes.
 * Fix: Create the missing directory and a CJS stub that re-exports from the main index.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";

// ── Patch 1: blakejs ESM shim ──────────────────────────────────────────────

const blakePkgPath = "./node_modules/blakejs/package.json";
const blakeShimPath = "./node_modules/blakejs/esm.mjs";

if (!existsSync(blakePkgPath)) {
  console.log("blakejs not found — skipping blakejs patch");
} else {
  const pkg = JSON.parse(readFileSync(blakePkgPath, "utf8"));

  if (pkg.exports) {
    console.log("blakejs already has exports — skipping blakejs patch");
  } else {
    pkg.exports = {
      ".": {
        import: "./esm.mjs",
        require: "./index.js",
        default: "./index.js",
      },
    };

    const shim = `// ESM re-export shim — auto-generated by patch-blakejs.mjs
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const pkg = require("./index.js");
export const {
  blake2b, blake2bHex, blake2bInit, blake2bUpdate, blake2bFinal,
  blake2s, blake2sHex, blake2sInit, blake2sUpdate, blake2sFinal,
} = pkg;
export default pkg;
`;

    writeFileSync(blakePkgPath, JSON.stringify(pkg, null, 2) + "\n");
    writeFileSync(blakeShimPath, shim);
    console.log("Patched blakejs: added ESM named-export shim");
  }
}

// ── Patch 2: @zk-kit/eddsa-poseidon missing CJS stub ──────────────────────

const eddsaPkgPath = "./node_modules/@zk-kit/eddsa-poseidon/package.json";
const eddsaCjsDir = "./node_modules/@zk-kit/eddsa-poseidon/dist/lib.commonjs";
const eddsaCjsStub = `${eddsaCjsDir}/eddsa-poseidon-blake-2b.cjs`;

if (!existsSync(eddsaPkgPath)) {
  console.log("@zk-kit/eddsa-poseidon not found — skipping eddsa-poseidon patch");
} else if (existsSync(eddsaCjsStub)) {
  console.log("@zk-kit/eddsa-poseidon CJS stub already exists — skipping");
} else {
  // Create the missing directory and CJS stub that delegates to the main CJS index
  mkdirSync(eddsaCjsDir, { recursive: true });

  const stub = `// CJS stub — auto-generated by patch-blakejs.mjs
// The published @zk-kit/eddsa-poseidon@1.1.0 is missing this file.
// We delegate to the main CJS bundle which contains the same exports.
"use strict";
const main = require("../index.cjs");
module.exports = main;
`;
  writeFileSync(eddsaCjsStub, stub);
  console.log("Patched @zk-kit/eddsa-poseidon: created missing CJS stub");
}
