/**
 * Patches blakejs to add an ESM re-export shim.
 *
 * Problem: @zk-kit/eddsa-poseidon is pure ESM and does named imports from blakejs,
 * which is CJS-only. Node.js 22 can't statically resolve named exports from CJS
 * modules whose exports depend on runtime require() calls.
 *
 * Fix: Add an `exports` field to blakejs/package.json pointing `import` at a
 * thin ESM wrapper that loads the CJS module via createRequire and re-exports.
 */
import { readFileSync, writeFileSync, existsSync } from "fs";

const pkgPath = "./node_modules/blakejs/package.json";
const shimPath = "./node_modules/blakejs/esm.mjs";

if (!existsSync(pkgPath)) {
  console.log("blakejs not found — skipping patch");
  process.exit(0);
}

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));

if (pkg.exports) {
  console.log("blakejs already has exports — skipping patch");
  process.exit(0);
}

pkg.exports = {
  ".": {
    import: "./esm.mjs",
    require: "./index.js",
    default: "./index.js",
  },
};

const shim = `// ESM re-export shim — auto-generated by patch-blakejs.mjs
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const pkg = require("./index.js");
export const {
  blake2b, blake2bHex, blake2bInit, blake2bUpdate, blake2bFinal,
  blake2s, blake2sHex, blake2sInit, blake2sUpdate, blake2sFinal,
} = pkg;
export default pkg;
`;

writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
writeFileSync(shimPath, shim);
console.log("Patched blakejs: added ESM named-export shim");
